
name: Test
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: echo "Hola, este es un mensaje de prueba"
       
       
